### PR TITLE
adding yuhow's abstract

### PR DESCRIPTION
**Pull request by yuhow**
no additional comment

### CODE REVIEW

**Comment by yungyuc** [comment]
@yuhow, this PR updates only the HTML file but not the markdown file (index.md).  Could you update both files?  After you update the markdown file, simply run make in the directory, the make file will call the script to generate the HTML file for you.

I will wait for your update before merging.

**Comment by yungyuc** [comment]
@Yuhow, what do you plan to do with this PR?

**Comment by yuhow** [comment]
ok I will update index.md file

**Comment by yuhow** [comment]
updating index.md

**Comment by yungyuc** [comment]
@yuhow thanks.  Once you get that done please use this PR to update/merge to the repo.

**Comment by yungyuc** [comment]
@yuhow you need to update the agenda table too.

**Comment by yuhow** [comment]
sorry for the missing. I have updated the agenda table in index.md.

**Comment by yungyuc** [comment]
And while updating the table in the markdown file, you should run make to update the HTML file too, so that the table will show in the website.

**Comment by yuhow** [comment]
ummm something is strange

**Comment by yungyuc** [comment]
This won't be a trivial merge because you have pushed another conflict change.  You need to resolve the conflict while merging.

**Comment by yuhow** [comment]
umm... don't really know how to solve this now. But I will try to figure it
out.

2015-11-27 15:48 GMT+08:00 Yung-Yu Chen notifications@github.com:

**Comment by yungyuc** [comment]
Usually you have to resolve the conflict locally.  Then push the merged changes to your repository to update this PR.  After that you should be able to merge this on Github.

**Pull request merged**
